### ISSUE TITLE
Need Refactor

### ISSUE THREAD

**Issue by ZQDesigned** [pzcn/Perfect-Icons-APP#7]
Yesterday, one of my app's user submitted a request to me from my official qq group, asking me to export a magisk module from this app.  
Unexpectedly, it threw an exception. This is the content.
```
java.lang.NullPointerException: page2Config must not be null
	at com.projectkr.shell.MainActivity$c.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
```
Then I tried to fix it. But when I pulled your code to my local machine and trying to fix this problem, I found that you are using Gradle 4.0 for this project. It means that it's not supported by Google officially. I'm trying to refactor your project  and migrate all the depecated code to make it suitable for the newest IDE. If you want to get this version of code, you may could create a new branch and provide a temporarily write access to this branch. Thanks.

**Comment by pzcn** [comment]
Thank you very much, I have invited you to be added as a collaborator

**Comment by ZQDesigned** [comment]
I have accepted your invitation. I will finish my refactor process and push my updated code ASAP. Glad to help you.
